### ISSUE TITLE
Example Low level v1arch agent (cmd responder) doesn't work with pysnmp 7.1.16

### ISSUE THREAD

**Issue by TeddyJack** [lextudio/pysnmp#167]
### Expected behavior

I expected this: example responds to request = "1.3.6.1.2.1.1.1.0" with value = "PySNMP example command responder"

### Actual behavior

Script starts fine until request being sent. Error in Python happens: AttributeError: 'AsyncioDispatcher' object has no attribute 'sendMessage'

### Detailed steps

1) Download example: /examples/v1arch/asyncio/agent/cmdrsp/implementing-scalar-mib-objects-over-ipv4-and-ipv6.py
changed port 161 -> 1161
2) pip install pysnmp
3) Run ireasoning MIB browser, load SNMPv2-MIB (standard MIB, located in program folder), set up port 1161
4) Executed GET command on 1.3.6.1.2.1.1.1.0
5) Python catches request, but error happens
Is this example outdated?
Couldn't find example of high level v1arch agent responder.

### Python package information

7.1.16

### Operating system information

Ubuntu 20.04

### Python information

3.10.16

### (Optional) Contents of your test script

```python
I used this script:
https://github.com/lextudio/pysnmp/blob/main/examples/v1arch/asyncio/agent/cmdrsp/implementing-scalar-mib-objects-over-ipv4-and-ipv6.py
changed port 161 -> 1161
```

### Relevant log output

```shell
This program needs to run as root/administrator to monitor port 161.
Started. Press Ctrl-C to stop
Exception in callback AbstractTransportDispatcher._callback_function(<pysnmp.carri...x7fb29fadee90>, ('127.0.0.1', 47630), b'0)\x02\x01\...1\x00\x05\x00')
handle: <Handle AbstractTransportDispatcher._callback_function(<pysnmp.carri...x7fb29fadee90>, ('127.0.0.1', 47630), b'0)\x02\x01\...1\x00\x05\x00')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/teddy/.local/lib/python3.10/site-packages/pysnmp/carrier/base.py", line 166, in _callback_function
    self.__recv_callables[recvId](
  File "/home/teddy/Projects/responder_low.py", line 120, in __callback
    transportDispatcher.sendMessage(
  File "/home/teddy/.local/lib/python3.10/site-packages/pysnmp/carrier/asyncio/dispatch.py", line 125, in __getattr__
    raise AttributeError(
AttributeError: 'AsyncioDispatcher' object has no attribute 'sendMessage'
```

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://www.pysnmp.com/support#commercial-support), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
The sample code wasn't up to date. Just fixed in the main branch and you can check it out.
