### ISSUE TITLE
TRAP/INFORM notification generates AttributeError

### ISSUE THREAD

**Issue by robmool** [lextudio/pysnmp#127]
### Expected behavior

I expected no error during the execution of the next example.

import asyncio
from pysnmp.hlapi.v1arch.asyncio import *

async def run():
    errorIndication, errorStatus, errorIndex, varBinds = await sendNotification(
        SnmpDispatcher(),
        CommunityData('public', mpModel=0),
        await UdpTransportTarget.create(('192.168.1.42', 9201)),
        'trap',
        NotificationType(
            ObjectIdentity('IAP-ALARMS-NOTIFICATIONS-MIB-ENT', 'iapSolutions', 1)
        ).addVarBinds(
            ('1.3.6.1.2.1.1.3.0', 12345),
            ('1.3.6.1.6.3.18.1.3.0', '192.168.1.44'),
            ('1.3.6.1.4.1.49323.1.1.1.1', OctetString('mytext'))
        )
    )
    print(errorIndication, errorStatus, errorIndex, varBinds)

asyncio.run(run())

### Actual behavior

Execution details:
Traceback (most recent call last):
  File "/home/robm/pytenms7/./trapnotif.py", line 22, in <module>
    asyncio.run(run())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/robm/pytenms7/./trapnotif.py", line 7, in run
    errorIndication, errorStatus, errorIndex, varBinds = await sendNotification(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robm/pytenms7/lib/python3.11/site-packages/pysnmp/hlapi/v1arch/asyncio/ntforg.py", line 232, in sendNotification
    v2c.apiTrapPDU.setVarBinds(reqPdu, inputVarBinds)
  File "/home/robm/pytenms7/lib/python3.11/site-packages/pysnmp/proto/api/v1.py", line 153, in setVarBinds
    apiVarBind.setOIDVal(varBindList.getComponentByPosition(idx), varBind)
  File "/home/robm/pytenms7/lib/python3.11/site-packages/pysnmp/proto/api/v1.py", line 44, in setOIDVal
    val.getTagSet(),
    ^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'getTagSet'

### Detailed steps

See above.

### Python package information

pysnmp 7.1.4

### Operating system information

Linux Debian 12.6

### Python information

3.11.2

### (Optional) Contents of your test script

```python
A simular example does work with pysnmp 6.2.6

import asyncio
from pysnmp.hlapi.asyncio import *

async def run():
    errorIndication, errorStatus, errorIndex, varBinds = await sendNotification(
        SnmpEngine(),
        CommunityData('public', mpModel=0),
        UdpTransportTarget(('192.168.1.42', 9201)),
        ContextData(),
        'trap',
        NotificationType(
            ObjectIdentity('IAP-ALARMS-NOTIFICATIONS-MIB-ENT', 'iapSolutions', 1)
        ).addVarBinds(
            ('1.3.6.1.2.1.1.3.0', 12345),
            ('1.3.6.1.6.3.18.1.3.0', '192.168.1.44'),
            ('1.3.6.1.4.1.49323.1.1.1.1', OctetString('mytext'))
        )
    )
    print(errorIndication, errorStatus, errorIndex, varBinds)

asyncio.run(run())
```

**Comment by lextm** [comment]
Your code didn't function properly due to the incompatibility between the data types expected by PySNMP and raw Python types. PySNMP requires the data to be in specific SNMP data types.

For more information, please refer to the following documentation:

https://docs.lextudio.com/pysnmp/v7.1/docs/snmp-design#data-types
